name: learn-github-actions
on: [push]

jobs:
  deploy-application:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          whoami
          ls -all
